config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admins, controllers: {
        sessions: "admins/sessions"
            }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ActionCable.server => '/cable'

  root "static_pages#home"
  devise_for :users, controllers: {
        registrations: "users/registrations",
        sessions: "users/sessions"
            }

  resources :hotel_reviews

  resources :reports, only: [:new, :create, :index, :destroy]

  resources :hotels do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  notify_to :users
  resources :users, only: [:show, :index]
  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]
  mount ActionCable.server => '/cable'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :reports, dependent: :destroy

  validates :body, presence: true
  validates :user_id, presence: true


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable
  before_action :find_comment, only: [:update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
    @comment = Comment.new
  end

  def create
    hotel_id = if params[:comment_id]
                  params[:comment][:hotel_id]
                else
                  params[:hotel_id]
                end
    if !@commentable
      flash[:danger] = t "error_parrent_comment_not_found"
      redirect_to hotel_url(hotel_id)
    else
      @comment = @commentable.comments.new comment_params
      if !@comment.save
        flash[:danger] = t "error_create_comment"
        redirect_to hotel_url(hotel_id)
      end
    end
  end

  def edit; end

  def update
    @comment.update_attributes body: params[:comment][:body]
  end

  def destroy
    return if @comment.destroy
    flash.now[:danger] = t "error_delete_comment"
  end

  private

  def comment_params
    params.require(:comment).permit :body, :user_id
  end

  def find_commentable
    @commentable = if params[:comment_id]
                     Comment.find_by id: params[:comment_id]
                   else
                     Hotel.find_by id: params[:hotel_id]
    end
  end

  def find_comment
    @comment = Comment.find_by id: params[:id]

    return if @comment
    flash.now[:danger] = t "error_comment_not_found"
    redirect_to hotels_url
  end

  def correct_user
    unless current_user.id == @comment.user.id || current_user.id == 1
      redirect_to hotels_url
    end
  end
end

app/views/comments/_comment.html.erb
<br>
<li class="clearfix" id="comment_overall<%= comment.id %>">
  <div class="row">
    <div class="avatar-icon col-md-1">
      <% if comment.user.picture %>
        <%= image_tag(comment.user.picture, class: "avatar")%>
      <% else %>
        <%= image_tag("user", class: "avatar") %>
        <%= comment.user.name %>
      <% end %>

    </div>

    <div class="col-md-10">
      <div class="post-comments">
        <p class="meta"><span id="comment_time<%= comment.id %>">
          <% if (comment.created_at == comment.updated_at) %>
            <%= comment.created_at.in_time_zone("Hanoi").strftime("%d/%m/%Y %H:%M") %></span>
          <% else %>
            <%= t "updated_at" %> <%= comment.updated_at.in_time_zone("Hanoi").strftime("%d/%m/%Y %H:%M") %></span>
          <% end %>
          <%= t "by" %> <%= comment.user.name %>
          <% if user_signed_in? && comment.user != current_user %>
            <%= link_to image_tag('chat.png', class: "chat1-icon"), new_personal_message_path(receiver_id: comment.user, hotel_id: @hotel.id) %>
          <% end %>
        </p>
        <% if comment.commentable_type == "Hotel" %>
          <i class="pull-right">
            <small><button class="btn-sm btn-success button<%= comment.id %>">
              <% if user_signed_in? %>返信<% end %>
            </button></small>
            <%if comment.user != current_user%>
            <small>
              <%= link_to  new_report_path(comment: comment.id), remote: true do %>
                <button class="btn-sm btn-danger button">報告
                </button>
              <% end %>
            </small>
            <% end %>
          </i>
          <div id="modal-window" class="modal fade" role="dialog"
            aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
              </div>
            </div>
          </div>
        <% end %>
        <p id="comment_body<%= comment.id %>">
          <%= comment.body %>
        </p>
        <% if user_signed_in? %>
          <% if comment.user == current_user %>
            <td><%= link_to "編集", edit_comment_path(comment), remote: true,
              class: "btn btn-warning buttom-size" %></td>
            <td><%= link_to "削除", comment_path(comment), method: :delete,
              remote: true, class: "btn btn-danger buttom-size",
              data: {confirm: "Are you sure?"} %>
            </td>
          <% end %>
        <% end %>
          <% if comment.commentable_type == "Hotel" %>
            <ul class="comments_comment<%= comment.id %>">
              <%= render comment.comments %>
            </ul>
            <div class="reply_form<%= comment.id %>">
            </div>
          <% end %>
        <% if user_signed_in? %>
          <script type="text/javascript">
            $(document).on("click",".button<%= comment.id %>",function(){
              $(".reply_form<%= comment.id %>").html("<%=j render partial: 'comments/form', locals: {:comment => comment} %>")
              $(".comment_user").val($("#user_hotel").val())
            });
          </script>
        <% end %>
      </div>
    </div>
  </div>
</li>

<style>
  .chat1-icon {
    width: 8%;
    height: 0%;
    margin-left: -30px;
  }
  .avatar-icon {
    padding-left: 75px;
  }
  .avatar {
    width: 75px;
    height: 70px;
  }
  .buttom-size {
    padding: 1px 5px;
  }
</style>

app/views/comments/_comment_other.html.erb
<li class="clearfix" id="comment_overall<%= comment.id %>">
  <div class="row">
    <div class="avatar-icon col-md-1">
      <% if comment.user.picture %>
        <%= image_tag(comment.user.picture, class: "avatar")%>
      <% else %>
        <%= image_tag("user", class: "avatar") %>
        <%= comment.user.name %>
      <% end %>
    </div>
    <div class="col-md-10">
      <div class="post-comments">
        <p class="meta"><span id="comment_time<%= comment.id %>">
          <% if (comment.created_at == comment.updated_at) %>
            <%= comment.created_at.in_time_zone("Hanoi").strftime("%d/%m/%Y %H:%M") %></span>
          <% else %>
            <%= t "updated_at" %> <%= comment.updated_at.in_time_zone("Hanoi").strftime("%d/%m/%Y %H:%M") %></span>
          <% end %>
          <%= t "by" %> <%= comment.user.name %>
          <% if user_signed_in? && comment.user != current_user %>
            <%= link_to image_tag('chat.jpg', class: "chat1-icon"), new_personal_message_path(receiver_id: comment.user), , hotel_id: @hotel.id %>
          <% end %>
        </p>
        <% if comment.commentable_type == "Hotel" %>
          <i class="pull-right">
            <small><button class="btn-sm btn-success button<%= comment.id %>">
              <% if user_signed_in? %><% end %>
            </button></small>
          </i>
        <% end %>
        <p id="comment_body<%= comment.id %>">
          <%= comment.body %>
        </p>
          <% if comment.commentable_type == "Hotel" %>
            <ul class="comments_comment<%= comment.id %>">
              <%= render comment.comments %>
            </ul>
            <div class="reply_form<%= comment.id %>">
            </div>
          <% end %>
          <% if user_signed_in? %>
            <script type="text/javascript">
              $(document).on("click",".button<%= comment.id %>",function(){
                if ( $("#user_hotel").val() === undefined ){
                  $(".button<%= comment.id %>").hide()
                } else {
                  $(".reply_form<%= comment.id %>").html("<%=j render partial: 'comments/form', locals: {:comment => comment} %>")
                  $(".comment_user").val($("#user_hotel").val())
                }
              })
            </script>
          <% end %>
      </div>
    </div>
  </div>
</li>

<style>
  .chat1-icon {
    width: 8%;
    height: 0%;
    margin-left: -30px;
  }
  .avatar-icon {
    padding-left: 75px;
  }
  .avatar {
    width: 75px;
    height: 70px;
  }
</style>

app/views/comments/_edit.html.erb
<div class="modal-header">
  <h3><%= t "edit" %></h3>
</div>
<%= render "edit_form" %>

app/views/comments/_edit_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for @comment, remote: true,
      html: {style: "display:inline;"} do |f| %>
      <div class="modal-body">
        <ul class="errors"></ul>

        <div class="form-group">
          <%= f.text_area :body, size: "30x5", class: "form-control" %>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to t("cancel"), "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<br>
<%= form_for :comment,
  url: comment_comments_path(:comment_id => comment.id),
  :html => {:class => "form-inline"}, remote: true do |f| %>
  <%= f.text_area :body, placeholder: "Add a reply",
    class: "box-clear", value: "" %><br/>
  <%= f.hidden_field :user_id, value: current_user.id, class: "comment_user" %>
  <%= f.hidden_field :hotel_id, value: comment.commentable_id %>
  <%= f.hidden_field :comment_id, value: comment.id %>
  <%= f.submit "Add Reply Comment", class: "btn btn-primary pull-right" %>
<% end %>
<br>
<br>

app/views/comments/create.js.erb
<% if @comment.commentable_type == "Hotel" %>
  $("#comments_hotel").append("<%= escape_javascript("#{render :partial => 'comments/comment', :locals => { :comment => @comment }}").html_safe %>");
  $("#comment_body").val("");
<% else %>
  $(".comments_comment".concat(<%= @comment.commentable_id.to_s %>)).append("<br><%= escape_javascript("#{render :partial => 'comments/comment', :locals => { :comment => @comment }}").html_safe %>");
  $("#comment_body").val("");
<% end %>

app/views/comments/destroy.js.erb
$("#comment_overall".concat(<%= @comment.id.to_s %>)).replaceWith('<li style="display: none;" id="comment_overall<%= @comment.id %>"></li>')

app/views/comments/edit.js.erb
$("#comment-modal").html("<%= escape_javascript(render 'edit') %>")
$("#comment-modal").modal("show")

app/views/comments/update.js.erb
$("ul.errors").html("")
<% if @comment.errors.any? %>
  <% @comment.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li/>").html('<%= message.html_safe %>'))
  <% end %>
<% else %>
  $("#comment_body".concat(<%= @comment.id.to_s %>)).replaceWith('<p id="comment_body<%= @comment.id %>"><%= @comment.body %></p>')
  $("#comment_time".concat(<%= @comment.id.to_s %>)).replaceWith('<span id="comment_time<%= @comment.id %>"><%= t "updated_at" %> <%= @comment.updated_at.in_time_zone("Hanoi").strftime("%d/%m/%Y %H:%M") %></span>')
  $("#comment-modal").modal("hide")
<% end %>