config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admins, controllers: {
        sessions: "admins/sessions"
            }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ActionCable.server => '/cable'

  root "static_pages#home"
  devise_for :users, controllers: {
        registrations: "users/registrations",
        sessions: "users/sessions"
            }

  resources :hotel_reviews

  resources :reports, only: [:new, :create, :index, :destroy]

  resources :hotels do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  notify_to :users
  resources :users, only: [:show, :index]
  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]
  mount ActionCable.server => '/cable'
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  belongs_to :hotel

  has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy

  validates :author, uniqueness: {scope: :receiver}

  scope :participating, -> (user) do
    where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
  end

  scope :between, -> (sender_id, receiver_id) do
    where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id))
  end

  def with(current_user)
    author == current_user ? receiver : author
  end

  def participates?(user)
    author == user || receiver == user
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, except: [:index]
  before_action :check_participating!, except: [:index]

  def index
    @conversations = Conversation.participating(current_user).order('updated_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @conversation = Conversation.find_by(id: params[:id])
    @personal_message = PersonalMessage.new
  end

  private

  def set_conversation
    @conversation = Conversation.find_by(id: params[:id])
  end

  def check_participating!
    redirect_to root_path unless @conversation && @conversation.participates?(current_user)
  end
end

app/views/conversations/_chat.html.erb
<div class="container text-center">
  <div class="row">
    <div class="chat-button">
      <button id="addClass" class="btn btn-light btn-long"><%= online_status @conversation.with(current_user) %></button>
    </div>
    <hr>
  </div>
</div>
<div class="popup-box chat-popup" id="qnimate">
  <div class="popup-head">
    <div class="popup-head-left pull-left">
      <%= online_status @conversation.with(current_user) %>
    </div>
    <div class="popup-head-right pull-right">
      <div class="btn-group">
      </div>
      <button data-widget="remove" id="removeClass"
        class="chat-header-button pull-right" type="button">
        <i class="glyphicon glyphicon-off"></i>
      </button>
    </div>
  </div>

  <div class="popup-messages" id="conversation-main">
    <div class="direct-chat-messages">
      <% if @conversation.personal_messages.all.length > 10 %>
        <button id="load-more" class="btn">
          <%= t "load_more" %>
        </button>
      <% end %>
      <% if @conversation.personal_messages.any? %>
        <div id="conversation-body" data-conversation-id="<%= @conversation.id %>">
          <% @conversation.personal_messages.each do |personal_message| %>
            <% if current_user == personal_message.user %>
              <%= render partial: "personal_messages/personal_message", locals: {personal_message: personal_message} %>
            <% else %>
              <%= render partial: "personal_messages/personal_message_other", locals: {personal_message: personal_message} %>
            <% end %>
          <% end %>
        </div>
      <% else %>
        <div class="card-body hidden" id="messages"></div>
      <% end %>
    </div>
  </div>
  <div class="popup-messages-footer">
    <%= form_for @personal_message do |f| %>
        <%= hidden_field_tag 'conversation_id', @conversation.id %>
        <%= f.text_area :body, class: "form-control" %>
        <%= hidden_field_tag 'current_user_id', current_user.id %>
        <%= f.submit %>
      <% end %>
  </div>
</div>
<script type="text/javascript">

</script>

app/views/conversations/_conversation.html.erb
<div>
  Chatting with <%= online_status conversation.with(current_user) %>
  <br>
  <em><%= conversation.personal_messages.last.body.truncate(50) %></em>
  <br>
  <%= link_to 'View conversation', hotel_path(:id => conversation.hotel.id, :conversation_id => conversation.id) %>

  <hr>
</div>

app/views/conversations/chat.js.erb
$('#messages').html('<%= escape_javascript render(@messages) %>');

app/views/conversations/index.html.erb
<h1>Your conversations</h1>

<div id="conversations">
  <%= render @conversations %>
</div>

app/views/conversations/index.js.erb
$('#conversations').replaceWith('<%= j render @conversations %>');

app/views/conversations/show.html.erb
<h1>Chatting with <%= @conversation.with(current_user).name %></h1>

<div id="conversation-main">
  <div id="conversation-body" data-conversation-id="<%= @conversation.id %>">
    <%= render @conversation.personal_messages %>
  </div>

  <%= form_for @personal_message do |f| %>
    <%= hidden_field_tag 'conversation_id', @conversation.id %>
    <%= f.label :body %>
    <%= f.text_area :body %>

    <%= f.submit %>
  <% end %>
</div>
<%= render "chat" %>